name: 'Setup Node with Cache'
description: 'Instala Node.js y configura caché de npm'
inputs:
  node_version:
    description: 'Versión de Node'
    default: '20'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
      shell: bash
