name: 'Deploy to Cloud Run'
description: 'Deploys to Google Cloud Run'

inputs:
  gcp_credentials:
    description: 'GCP credentials'
    required: true
  project_id:
    description: 'GCP project ID'
    required: true
  service_name:
    description: 'Cloud Run service name'
    required: true
  image:
    description: 'Docker image to deploy'
    required: true
  region:
    description: 'GCP region'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: \${{ inputs.gcp_credentials }}

    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: \${{ inputs.service_name }}
        image: \${{ inputs.image }}
        project_id: \${{ inputs.project_id }}
        region: \${{ inputs.region }}
