on:
  workflow_call:
    inputs:
      skip_test: { type: boolean, default: false }
    secrets:
      SONAR_TOKEN: { required: false }

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-cache # Llama a la acción anterior
      
      # Stage 4: Horusec
      - name: Horusec SAST Scan
        run: |
          curl -fsSL https://githubusercontent.com | bash -s latest
          horusec start -p="./" -e="true"

      # Stage 7: Unit Test
      - name: Unit Tests
        if: ${{ !inputs.skip_test }}
        run: npm test

      # Stage 8: SonarQube
      - name: SonarQube Analysis
        if: hashFiles('sonar-project.properties') != ''
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://tu-empresa.net
