name: "CI Node.js Pipeline"

on:
  workflow_call:
    inputs:
      project_name: { type: string, required: true }
      acr_name: { type: string, required: true }
      node_version: { type: string, default: '20' }
      skip_test: { type: boolean, default: false }
    secrets:
      AZURE_CREDENTIALS: { required: true }
      SONAR_TOKEN: { required: false }

jobs:
  scan:
    uses: ./.github/workflows/build-scan-quality.yml
    with:
      skip_test: ${{ inputs.skip_test }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    needs: scan # Solo publica si el scan pasa (Quality Gate)
    uses: ./.github/workflows/publish-artifact.yml
    with:
      acr_name: ${{ inputs.acr_name }}
      image_name: ${{ inputs.project_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
